# Generated by Django 4.2.13 on 2024-06-26 07:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='@gmail.com', max_length=254)),
                ('photo', models.ImageField(upload_to='images/')),
                ('about_product', models.TextField()),
                ('description', models.FileField(upload_to='descriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AlterField(
            model_name='topfive',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='ReviewsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stars', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviews_sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_product', to='sport_app.sport_list')),
            ],
        ),
    ]
