# Generated by Django 4.2.13 on 2024-06-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0002_sport_list_alter_topfive_photo_reviewsproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=110)),
                ('tags', models.ManyToManyField(to='sport_app.tag')),
            ],
        ),
    ]
